name: Utiliser un secret GitHub

on:
  push:
    branches:
      - main

jobs:
  show-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Afficher le secret masqué
        run: echo "La clé API est ${{ secrets.API_KEY }}"
