name: Hello World Workflow

# Le workflow se déclenche à chaque push sur la branche main
on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest  # Machine virtuelle Ubuntu

    steps:
      - name: Dire bonjour
        run: echo "Hello World"
